export * from './lib/products.module';
export * from './lib/models/category';
export * from './lib/models/products';
export * from './lib/service/products.service';
export * from './lib/service/categories.service';
export * from './lib/pages/products-list/products-list.component';
export * from './lib/pages/product-set/product-set.component';
export * from './lib/pages/product-page/product-page.component';
export * from './lib/pages/galary/galary.component';
